apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./deploy
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: migration
  name: migration
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: migration
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ./deploy
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: migration
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: production
          image: biem97/lilreddit-migration:latest
          name: migration
          resources: {}
      restartPolicy: Always
status: {}
