apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./deploy
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ./deploy
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: redis
    spec:
      containers:
        - env:
            - name: REDIS_PASSWORD
              value: redispassword
          image: bitnami/redis:6.2
          name: redis
          ports:
            - containerPort: 6379
          resources: {}
          volumeMounts:
            - mountPath: /bitnami/redis/data
              name: redis-volume
      restartPolicy: Always
      volumes:
        - name: redis-volume
          persistentVolumeClaim:
            claimName: redis-volume
status: {}
