apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./deploy
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ./deploy
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: server
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: production
            - name: REDIS_PASSWORD
              value: redispassword
          image: biem97/lilreddit-server:latest
          name: server
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
